site_name:           Lexicon.jl
repo_url:            https://github.com/MichaelHatherly/Lexicon.jl
site_description:    Julia package documentation generator.
site_author:         Michael Hatherly
theme:               flatly
markdown_extensions: [tables, fenced_code]
pages:
- Introduction: index.md
- Manual:
  - Overview: manual.md
- API:
  - Lexicon: api/Lexicon.md
  - Index: api/index.md

